#!/bin/bash --login
cd $(dirname $0)/../..

export PIPENV_VENV_IN_PROJECT=true

which pipenv
if [ $? != 0 ]
then
  echo "Missing prerequisite pipenv, bailing out"
  exit 1
fi


pipenv --venv
if [ $? != 0 ]
then
  echo "Creating virtualenv for locationsharinglib"
  pipenv install --dev
fi
